apiVersion: v1
kind: Service
metadata:
  name: vertica
  labels:
    app: vertica
spec:
  type: LoadBalancer
  ports:
  - port: 5433
    name: vertica
  selector:
    app: vertica
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vertica
spec:
  serviceName: "vertica"
  replicas: 1
  selector:
    matchLabels:
      app: vertica
  template:
    metadata:
      labels:
        app: vertica
    spec:
      containers:
      - name: vertica
        image: docker.io/bryanherger/vertica_eon:latest
        env:
        - name: IS_KUBERNETES
          value: "true"
        ports:
        - containerPort: 5433
          name: vertica
        volumeMounts:
        - name: verticasshkeys
          mountPath: "/mnt/verticakeys"
          readOnly: true
      volumes:
      - name: verticasshkeys
        secret:
          secretName: verticasshkeys
